# -*- coding: utf-8 -*-
"""MAST679_FinalProject_Hackett_Kolla

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BFR5Oy2VgRHN8Aceiq5nxQp5yRRhlPTu
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

# data
df = pd.read_csv("gps_data.csv")

df_clean = df.dropna(subset=['location-long','location-lat']).copy()

df_clean['timestamp'] = pd.to_datetime(df_clean['timestamp'])
df_clean['time_seconds'] = df_clean['timestamp'].dt.hour * 3600 + \
                           df_clean['timestamp'].dt.minute * 60 + \
                           df_clean['timestamp'].dt.second

X = df_clean[['location-long','location-lat']]
y = df_clean['time_seconds']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=17)

scalar = StandardScaler()
X_train_scaled = scalar.fit_transform(X_train)
X_test_scaled = scalar.transform(X_test)

lr_model =LinearRegression()
knn_model = KNeighborsRegressor(n_neighbors=5)
rf_model = RandomForestRegressor(n_estimators=100, random_state=17)

lr_model.fit(X_train_scaled, y_train)
knn_model.fit(X_train_scaled, y_train)
rf_model.fit(X_train_scaled, y_train)

lr_preds = lr_model.predict(X_test_scaled)
knn_preds = knn_model.predict(X_test_scaled)
rf_preds = rf_model.predict(X_test_scaled)

lr_mae = mean_absolute_error(y_test, lr_preds)
knn_mae = mean_absolute_error(y_test, knn_preds)
rf_mae = mean_absolute_error(y_test, rf_preds)

print(f"Linear Regression MAE: {lr_mae:.2f} seconds")
print(f"K-Nearest Neighbours MAE: {knn_mae:.2f} seconds")
print(f"Random Forest Regression MAE: {rf_mae:.2f} seconds")

import pandas as pd
import geopandas as gpd
from shapely.geometry import Point, MultiPoint, Polygon
from scipy.stats import gaussian_kde
import matplotlib.pyplot as plt
import numpy as np
from skimage import measure

# Load dataset

df = pd.read_csv("gps_data.csv")

# Rename
LAT_COL = "location-lat"
LON_COL = "location-long"
ID_COL = "individual-local-identifier"

# Drop rows with missing coordinates
df = df.dropna(subset=[LAT_COL, LON_COL])

# Create GeoDataFrame in WGS84 (for geographic locations), then project to UTM 18N (North America)
gdf = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(df[LON_COL], df[LAT_COL]),
    crs="EPSG:4326"
).to_crs(epsg=32618)

# Loop through each bird ID
unique_ids = gdf[ID_COL].unique()

for bird_id in unique_ids:
    bird_points = gdf[gdf[ID_COL] == bird_id]

    if bird_points.shape[0] < 5:
        print(f"Skipping bird {bird_id} (too few points)")
        continue

    # MCP
    mcp = MultiPoint(bird_points.geometry.tolist()).convex_hull
    mcp_area_km2 = mcp.area / 1e6

    # KDE
    x = bird_points.geometry.x
    y = bird_points.geometry.y
    kde = gaussian_kde(np.vstack([x, y]))

    # Grid
    xmin, xmax = x.min() - 500, x.max() + 500
    ymin, ymax = y.min() - 500, y.max() + 500
    xx, yy = np.mgrid[xmin:xmax:300j, ymin:ymax:300j]
    positions = np.vstack([xx.ravel(), yy.ravel()])
    kde_values = np.reshape(kde(positions).T, xx.shape)

    # 95% threshold
    flat_kde = kde_values.flatten()
    kde_threshold = np.percentile(flat_kde, 5)
    mask = kde_values >= kde_threshold

    # Extract contours
    contours = measure.find_contours(mask.astype(float), 0.5)
    kde_polygons = []

    for contour in contours:
        if len(contour) < 4:
            continue  # Need enough points for valid polygon

        contour_coords = np.column_stack((
            xmin + (xmax - xmin) * contour[:, 1] / 300,
            ymin + (ymax - ymin) * contour[:, 0] / 300
        ))

        try:
            poly = Polygon(contour_coords)
            if poly.is_valid and poly.area > 0:
                kde_polygons.append(poly)
        except Exception as e:
            print(f"Invalid KDE polygon for {bird_id}: {e}")
            continue

    kde_union = gpd.GeoSeries(kde_polygons).union_all()
    kde_area_km2 = kde_union.area / 1e6 if not kde_union.is_empty else 0

    # Plot
    fig, axes = plt.subplots(1, 2, figsize=(12, 6))
    fig.suptitle(f"Bird {bird_id}\nMCP Area: {mcp_area_km2:.2f} km² | KDE 95% Area: {kde_area_km2:.2f} km²")

    # MCP Plot
    bird_points.plot(ax=axes[0], color="blue", markersize=5)
    gpd.GeoSeries([mcp]).plot(ax=axes[0], edgecolor="red", facecolor="none", linewidth=2)
    axes[0].set_title("Minimum Convex Polygon (MCP)")

    # KDE Plot
    axes[1].imshow(np.rot90(kde_values), cmap="viridis", extent=[xmin, xmax, ymin, ymax])
    bird_points.plot(ax=axes[1], color="red", markersize=2)

    if not kde_union.is_empty:
        gpd.GeoSeries([kde_union]).plot(ax=axes[1], edgecolor="black", facecolor="none", linewidth=1)
    else:
        axes[1].text(0.5, 0.5, "No KDE contour", transform=axes[1].transAxes,
                     ha="center", va="center", fontsize=12, color="gray")

    axes[1].set_title("Kernel Density Estimation (95%)")
    plt.tight_layout()
    plt.show()

    print(f"Bird {bird_id}: MCP = {mcp_area_km2:.2f} km² | KDE 95% = {kde_area_km2:.2f} km²")

"""KDE relies on estimating a smooth denisty surface. Many of the KDE outputs are 0, which is likely caused by the tight clustering of the birds locations.

KDE assumes independent data (as opposed to autocorrelated data, which we have), so it makes sense that it is not working well in this case.
"""

# ================================================================
#  PURPLE MARTIN – FORAGING-RANGE COMPARISON
#    • Minimum-Convex Polygon  (MCP)
#    • Kernel-Density Estimate (KDE95)
#    • k-Local Convex Hull      (k-LoCoH)
# ---------------------------------------------------------------
#  Plug-and-play: just change FILE path, column names and EPSG zone
# ================================================================

# ── 0. ONE-OFF INSTALL (Colab) ───────────────────────────────────
!pip install --quiet geopandas contextily shapely pyproj scikit-learn rasterio

# ── 1. Imports ──────────────────────────────────────────────────
import pandas as pd, numpy as np, geopandas as gpd
import matplotlib.pyplot as plt, contextily as ctx

from shapely.geometry import Point, MultiPoint, Polygon, shape
from shapely.ops import unary_union
from sklearn.neighbors import NearestNeighbors
from scipy.stats import gaussian_kde
from rasterio import features
from rasterio.transform import from_origin
from matplotlib.patches import Patch

# ── 2. CONFIGURATION ────────────────────────────────────────────
FILE      = "gps_data.csv"            # raw data file
LAT_COL   = "location-lat"
LON_COL   = "location-long"
ID_COL    = "individual-local-identifier"
UTM_EPSG  = 32618                     # UTM zone of your study area
K_LOCOH   = 10                        # k for k-LoCoH  (tweak!)

# ── 3. Load & clean ---------------------------------------------------------
df = pd.read_csv(FILE)
df = df.dropna(subset=[LAT_COL, LON_COL])
gdf = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(df[LON_COL], df[LAT_COL]),
    crs="EPSG:4326"
).to_crs(epsg=UTM_EPSG)

# ── 4. Helper: KDE95 polygon (static bandwidth) -----------------------------
def kde95_polygon(xy, bandwidth=100, cell=250, level=0.95):
    if len(xy) < 5:
        return None
    kde = gaussian_kde(xy.T)
    xmin, ymin = xy.min(0) - 3*bandwidth
    xmax, ymax = xy.max(0) + 3*bandwidth
    nx = int((xmax - xmin) / cell) + 1
    ny = int((ymax - ymin) / cell) + 1
    xx, yy = np.mgrid[xmin:xmax:nx*1j, ymin:ymax:ny*1j]
    zz = kde(np.vstack([xx.ravel(), yy.ravel()])).reshape(xx.shape)

    thresh = np.percentile(zz, (1-level)*100)     # 5-th percentile for 95 %
    mask   = (zz >= thresh).astype("uint8")

    shapes = features.shapes(
        mask,
        transform=from_origin(xmin, ymax, cell, cell)
    )
    polys = [shape(geom) for geom, val in shapes if val == 1]
    return unary_union(polys) if polys else None

# ── 5. Loop through birds ---------------------------------------------------
for bird_id in gdf[ID_COL].unique():
    pts  = gdf[gdf[ID_COL] == bird_id]
    if len(pts) < max(5, K_LOCOH):
        print(f"Skipping {bird_id}: too few fixes")
        continue

    xy = np.column_stack([pts.geometry.x, pts.geometry.y])

    # 5-A MCP (100 %) --------------------------------------------------------
    mcp_poly = MultiPoint(xy).convex_hull
    mcp_area = mcp_poly.area / 1e6               # km²

    # 5-B KDE95 --------------------------------------------------------------
    kde_poly = kde95_polygon(xy, bandwidth=100, cell=250)
    kde_area = kde_poly.area / 1e6 if kde_poly else np.nan

    # 5-C k-LoCoH ------------------------------------------------------------
    nbr = NearestNeighbors(n_neighbors=K_LOCOH).fit(xy)
    neigh_ix = nbr.kneighbors(return_distance=False)
    hulls = [MultiPoint(xy[ix]).convex_hull for ix in neigh_ix]
    locoh_poly = unary_union(hulls)
    locoh_area = locoh_poly.area / 1e6           # km²

    # ── 6. Plot -------------------------------------------------------------
    fig, ax = plt.subplots(figsize=(8, 8))
    base = pts.to_crs(epsg=3857)
    base.plot(ax=ax, color="blue", markersize=3, alpha=0.6, label="Fixes")

    # project polygons to Web-Mercator
    mcp_web   = gpd.GeoSeries([mcp_poly],  crs=gdf.crs).to_crs(epsg=3857)
    locoh_web = gpd.GeoSeries([locoh_poly], crs=gdf.crs).to_crs(epsg=3857)

    mcp_web.boundary.plot(  ax=ax, edgecolor="red",  linewidth=1.2, linestyle="--", label="MCP")
    locoh_web.boundary.plot(ax=ax, edgecolor="green",linewidth=1.2, label=f"LoCoH k={K_LOCOH}")

    if kde_poly:
        kde_web = gpd.GeoSeries([kde_poly], crs=gdf.crs).to_crs(epsg=3857)
        kde_web.plot(ax=ax, facecolor="none", edgecolor="black", linewidth=1, label="KDE95")

    ctx.add_basemap(ax, source=ctx.providers.OpenStreetMap.Mapnik, attribution=False)
    ax.set_axis_off()
    ax.set_title(
        f"{bird_id}\nMCP: {mcp_area:.2f} km² | KDE95: {kde_area:.2f} km² | LoCoH-k: {locoh_area:.2f} km²"
    )
    legend_elements = [
    Patch(facecolor='none', edgecolor='red',  linestyle='--', label='MCP'),
    Patch(facecolor='none', edgecolor='black', label='KDE95'),
    Patch(facecolor='none', edgecolor='green', label=f'LoCoH k={K_LOCOH}'),
    plt.Line2D([0], [0], marker='o', color='w', label='Fixes', markerfacecolor='blue', markersize=5, alpha=0.6)
    ]
    ax.legend(handles=legend_elements)
    plt.tight_layout()
    plt.show()

    print(f"{bird_id}: MCP={mcp_area:.2f} km², KDE95={kde_area:.2f} km², LoCoH-k={locoh_area:.2f} km²")

import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
from sklearn.neighbors import KernelDensity

# 1. Load data
df = pd.read_csv("GPS_data.csv")

# 2. Select one bird (example: first bird ID)
bird_id = df['individual-local-identifier'].iloc[0]  # or pick a specific bird
bird_data = df[df['individual-local-identifier'] == bird_id]

# 3. Extract coordinates
X = bird_data[['location-lat', 'location-long']].values

# 4. Define bandwidths to test
bandwidths = np.linspace(0.0001, 0.01, 30)

# 5. Setup cross-validation
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# 6. Grid search for the best bandwidth
grid = GridSearchCV(KernelDensity(kernel='gaussian'),
                    {'bandwidth': bandwidths},
                    cv=kfold)
grid.fit(X)

# 7. Best bandwidth
best_bandwidth = grid.best_params_['bandwidth']
print(f"Best bandwidth: {best_bandwidth}")

# 8. Fit KDE with the best bandwidth
kde = KernelDensity(kernel='gaussian', bandwidth=best_bandwidth)
kde.fit(X)

# ================================================================
#   KDE Home Range Estimation for a Single Bird ("A127")
#   • Using SciPy only (gaussian_kde)
#   • Bandwidth selection:
#       - Unbiased CV (UCV)
#       - Leave-One-Out Likelihood (manual MLCV)
#       - Scott's Rule of Thumb
# ---------------------------------------------------------------
# ================================================================

# ── 1. Imports ──────────────────────────────────────────────────
import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

from shapely.geometry import shape
from shapely.ops import unary_union
from scipy.stats import gaussian_kde
from scipy.spatial.distance import pdist
from rasterio import features
from rasterio.transform import from_origin
import contextily as ctx

# ── 2. CONFIGURATION ────────────────────────────────────────────
FILE      = "gps_data.csv"
LAT_COL   = "location-lat"
LON_COL   = "location-long"
ID_COL    = "individual-local-identifier"
UTM_EPSG  = 32618                     # adjust to your UTM zone

GRID_H    = np.linspace(100, 1200, 30) # bandwidth candidates
CELL      = 250                       # grid cell size for raster
LEVEL     = 0.95                      # 95% contour

BIRD_ID   = "A114"

# ── 3. Helper functions ─────────────────────────────────────────
def gaussian_kernel(u2):
    return (2 * np.pi)**-1 * np.exp(-0.5 * u2)

def convolved_kernel(u2):
    return (4 * np.pi)**-1 * np.exp(-0.25 * u2)

def pairwise_sqdist(xy):
    return pdist(xy, metric='sqeuclidean')

def unbiased_cv(xy):
    """Unbiased Least-Squares Cross-Validation (UCV)."""
    n, d2 = len(xy), pairwise_sqdist(xy)
    best_h, best_score = None, np.inf
    for h in GRID_H:
        h2 = h * h
        t1 = (1/(n*(n-1)*h2)) * np.sum(convolved_kernel(d2/h2))
        t2 = (2/(n*h2)) * np.sum(gaussian_kernel(d2/h2))
        score = t1 - t2
        if score < best_score:
            best_h, best_score = h, score
    return best_h

def mlcv_manual(xy):
    """Manual Leave-One-Out Likelihood CV."""
    n = len(xy)
    best_h, best_score = None, -np.inf
    for h in GRID_H:
        scores = []
        for i in range(n):
            leave_one_out = np.delete(xy, i, axis=0)
            kde = gaussian_kde(leave_one_out.T, bw_method=h/np.std(leave_one_out, 0).mean())
            score = np.log(kde(xy[i]))
            scores.append(score)
        avg_score = np.mean(scores)
        if avg_score > best_score:
            best_h, best_score = h, avg_score
    return best_h

def scott_rule(xy):
    """Scott's rule of thumb."""
    n, d = len(xy), xy.shape[1]
    factor = n ** (-1. / (d + 4))
    avg_std = np.std(xy, axis=0).mean()
    return factor * avg_std

def kde95_polygon(xy, h):
    kde = gaussian_kde(xy.T, bw_method=h/np.std(xy, 0).mean())

    xmin, ymin = xy.min(0) - 3*h
    xmax, ymax = xy.max(0) + 3*h
    nx = int((xmax - xmin)/CELL) + 1
    ny = int((ymax - ymin)/CELL) + 1

    xx, yy = np.mgrid[xmin:xmax:nx*1j, ymin:ymax:ny*1j]
    zz = kde(np.vstack([xx.ravel(), yy.ravel()])).reshape(xx.shape)

    threshold = np.percentile(zz, (1-LEVEL)*100)
    mask = (zz >= threshold).astype("uint8")

    shapes_iter = features.shapes(mask, transform=from_origin(xmin, ymax, CELL, CELL))
    polys = [shape(geom) for geom, val in shapes_iter if val == 1]
    return unary_union(polys) if polys else None

# ── 4. Load data & extract bird ─────────────────────────────────
df = pd.read_csv(FILE).dropna(subset=[LAT_COL, LON_COL])
gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df[LON_COL], df[LAT_COL]), crs="EPSG:4326").to_crs(epsg=UTM_EPSG)

bird = gdf[gdf[ID_COL] == BIRD_ID]
if bird.empty:
    raise ValueError(f"No data found for bird '{BIRD_ID}'.")

xy = np.column_stack([bird.geometry.x, bird.geometry.y])

# ── 5. Bandwidth selection ──────────────────────────────────────
h_ucv = unbiased_cv(xy)
h_mlcv = mlcv_manual(xy)
h_scott = scott_rule(xy)

bandwidths = {'UCV': h_ucv, 'MLCV': h_mlcv, 'Scott': h_scott}

# ── 6. Build polygons & plot ────────────────────────────────────
COLORS = dict(UCV='green', MLCV='red', Scott='blue')
results = {}

for label, h in bandwidths.items():
    poly = kde95_polygon(xy, h)
    area = poly.area / 1e6 if poly else np.nan
    results[label] = dict(h=h, poly=poly, area=area)

fig, ax = plt.subplots(figsize=(8, 8))
bird.to_crs(3857).plot(ax=ax, marker='o', color='black', alpha=0.5, markersize=5, label="GPS fixes")

for label, d in results.items():
    if d['poly'] is not None:
        gpd.GeoSeries([d['poly']], crs=UTM_EPSG).to_crs(3857).boundary.plot(
            ax=ax, edgecolor=COLORS[label], linewidth=2, label=f"{label}  h={d['h']:.0f} m  A={d['area']:.2f} km²"
        )

ctx.add_basemap(ax, source=ctx.providers.OpenStreetMap.Mapnik, attribution=False)
ax.set_title(f"{BIRD_ID} – Home Range KDE 95%")
ax.set_axis_off()
ax.legend()
plt.tight_layout()
plt.show()

# ── 7. Console Summary ──────────────────────────────────────────
print(f"\n{BIRD_ID} – KDE 95% Home Range Summary:")
print(" Method   h*(m)   Area(km²)")
for label, d in results.items():
    print(f" {label:6s}  {d['h']:6.0f}   {d['area']:7.2f}")

pip install geopandas contextily shapely rasterio scipy