# -*- coding: utf-8 -*-
"""FinalProjectCode_Hackett_Kolla.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hQOYoqp0hGt9hrsgdilvtqYzzzcaY52P

# Source Code for Analysis and Results for Purple Martin Case Study

## Packages and Data
"""

# Packages

# Run the following line of code to install necessary packages
# !pip install geopandas contextily shapely rasterio scipy pyproj

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from shapely.geometry import Polygon
from scipy.spatial import ConvexHull
import contextily as ctx
import numpy as np
from pyproj import CRS
from shapely.geometry import shape
from shapely.ops import unary_union
from scipy.stats import gaussian_kde
from scipy.spatial.distance import pdist
from rasterio import features
from rasterio.transform import from_origin
from sklearn.neighbors import NearestNeighbors
from shapely.geometry import MultiPoint
from shapely.geometry import Polygon, MultiPoint, shape

# Loading Data
# Data 'gps_data.csv' taken from: https://www.movebank.org/cms/webapp?gwt_fragment=page%3Dstudies%2Cpath%3Dstudy1910442974
# Will need to upload the file into google collab

BIRD_ID = "A114"
FILE = "gps_data.csv"

df = pd.read_csv(FILE).dropna(subset=['location-lat', 'location-long'])
gdf = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(df['location-long'], df['location-lat']),
    crs="EPSG:4326"
)

"""## Minimum Convex Polygon (Section 3.3.1)

Minimum Convex Polygon (MCP) is the smallest polygon that contains all GPS data points for an individual bird, in our case, bird A114.

The area found by MCP is 0.93km^2, which could be used as an estimate for this bird's home range. However, this method often over estimates the range because it is sensitive to outliers.
"""

# UTM zone
longitude = gdf.geometry.x.mean()
utm_zone = int((longitude + 180)/6) + 1
UTM_EPSG = 32600 + utm_zone  # For northern hemisphere

# Convert to UTM
gdf_utm = gdf.to_crs(epsg=UTM_EPSG)

# Filter for Bird ID
gdf_A114 = gdf_utm[gdf_utm['individual-local-identifier'] == BIRD_ID]

# Extract coordinates and compute Convex Hull
coords = np.column_stack((gdf_A114.geometry.x, gdf_A114.geometry.y))
hull = ConvexHull(coords)
hull_points = coords[hull.vertices]
mcp_poly = Polygon(hull_points)

# Calculate area in km² (UTM is in meters)
mcp_area = mcp_poly.area / 1e6

# Plot
fig, ax = plt.subplots(figsize=(10, 10))

# Plot points (convert to Web Mercator for basemap)
gdf_A114_web = gdf_A114.to_crs(epsg=3857)
gdf_A114_web.plot(ax=ax, color='red', markersize=5, label='GPS points')

# Plot MCP border (convert to Web Mercator)
mcp_web = gpd.GeoSeries([mcp_poly], crs=gdf_utm.crs).to_crs(epsg=3857)
mcp_web.boundary.plot(ax=ax, color='blue', linewidth=1.5,
                     label=f'MCP (Area: {mcp_area:.2f} km²)')

# basemap
ctx.add_basemap(ax, source=ctx.providers.OpenStreetMap.Mapnik, attribution=False)
ax.set_title(f"{BIRD_ID} - Home Range (Minimum Convex Polygon)")
ax.set_axis_off()
ax.legend()
plt.tight_layout()
plt.show()

"""## Kernel Density Estimator (Section 3.3.2)

Kernel Density Estimator (KDE) estimates the utilization distribution. This method shows core use areas of the bird while reducing the outlier effect. However, this method can be sensitive to bandwidth and can include unused areas. This method also assume independence of all data points.

Selection of bandwidth is important in KDE because it determines the smoothness of the resulting density estimate. Bandwidth can be found by 'rule of thumb' or cross validation. We use unbiased cross validation, leave-one-out cross validation, and Scott's rule of thumb.

Unbiased Cross-Validation (UCV) minimizes the integrated square error of the density estimate to select an optimal bandwidth.

Manual Leave-One-Out Cross-Validation (MLCV) evaluates the likelihood of each data point being generated by the KDE model, which is trained on the remaining data points

Scott's Rule of Thumb provides a straightforward calculation for bandwidth based on the data's variance and sample size.

We chose to use Scott's Rule of Thumb in our final analysis, as this is typically the standard for KDE, which gives a home range estimate of 5.88km^2
"""

FILE      = "gps_data.csv"
LAT_COL   = "location-lat"
LON_COL   = "location-long"
ID_COL    = "individual-local-identifier"
UTM_EPSG  = 32618

GRID_H    = np.linspace(100, 1200, 30) # bandwidth candidates
CELL      = 250                       # grid cell size for raster
LEVEL     = 0.95                      # 95% contour

BIRD_ID   = "A114"

# functions
def gaussian_kernel(u2):
    return (2 * np.pi)**-1 * np.exp(-0.5 * u2)

def convolved_kernel(u2):
    return (4 * np.pi)**-1 * np.exp(-0.25 * u2)

def pairwise_sqdist(xy):
    return pdist(xy, metric='sqeuclidean')

def unbiased_cv(xy):
    """Unbiased Least-Squares Cross-Validation (UCV)."""
    n, d2 = len(xy), pairwise_sqdist(xy)
    best_h, best_score = None, np.inf
    for h in GRID_H:
        h2 = h * h
        t1 = (1/(n*(n-1)*h2)) * np.sum(convolved_kernel(d2/h2))
        t2 = (2/(n*h2)) * np.sum(gaussian_kernel(d2/h2))
        score = t1 - t2
        if score < best_score:
            best_h, best_score = h, score
    return best_h

def mlcv_manual(xy):
    """Manual Leave-One-Out Likelihood CV."""
    n = len(xy)
    best_h, best_score = None, -np.inf
    for h in GRID_H:
        scores = []
        for i in range(n):
            leave_one_out = np.delete(xy, i, axis=0)
            kde = gaussian_kde(leave_one_out.T, bw_method=h/np.std(leave_one_out, 0).mean())
            score = np.log(kde(xy[i]))
            scores.append(score)
        avg_score = np.mean(scores)
        if avg_score > best_score:
            best_h, best_score = h, avg_score
    return best_h

def scott_rule(xy):
    """Scott's rule of thumb."""
    n, d = len(xy), xy.shape[1]
    factor = n ** (-1. / (d + 4))
    avg_std = np.std(xy, axis=0).mean()
    return factor * avg_std

def kde95_polygon(xy, h):
    kde = gaussian_kde(xy.T, bw_method=h/np.std(xy, 0).mean())

    xmin, ymin = xy.min(0) - 3*h
    xmax, ymax = xy.max(0) + 3*h
    nx = int((xmax - xmin)/CELL) + 1
    ny = int((ymax - ymin)/CELL) + 1

    xx, yy = np.mgrid[xmin:xmax:nx*1j, ymin:ymax:ny*1j]
    zz = kde(np.vstack([xx.ravel(), yy.ravel()])).reshape(xx.shape)

    threshold = np.percentile(zz, (1-LEVEL)*100)
    mask = (zz >= threshold).astype("uint8")

    shapes_iter = features.shapes(mask, transform=from_origin(xmin, ymax, CELL, CELL))
    polys = [shape(geom) for geom, val in shapes_iter if val == 1]
    return unary_union(polys) if polys else None

df = pd.read_csv(FILE).dropna(subset=[LAT_COL, LON_COL])
gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df[LON_COL], df[LAT_COL]), crs="EPSG:4326").to_crs(epsg=UTM_EPSG)

bird = gdf[gdf[ID_COL] == BIRD_ID]
if bird.empty:
    raise ValueError(f"No data found for bird '{BIRD_ID}'.")

xy = np.column_stack([bird.geometry.x, bird.geometry.y])

# Bandwidth selection
h_ucv = unbiased_cv(xy)
h_mlcv = mlcv_manual(xy)
h_scott = scott_rule(xy)

bandwidths = {'UCV': h_ucv, 'MLCV': h_mlcv, 'Scott': h_scott}

# polygons
COLORS = dict(UCV='green', MLCV='blue', Scott='red')
results = {}

for label, h in bandwidths.items():
    poly = kde95_polygon(xy, h)
    area = poly.area / 1e6 if poly else np.nan
    results[label] = dict(h=h, poly=poly, area=area)

fig, ax = plt.subplots(figsize=(8, 8))
bird.to_crs(3857).plot(ax=ax, marker='o', color='black', alpha=0.5, markersize=5, label="GPS fixes")

for label, d in results.items():
    if d['poly'] is not None:
        gpd.GeoSeries([d['poly']], crs=UTM_EPSG).to_crs(3857).boundary.plot(
            ax=ax, edgecolor=COLORS[label], linewidth=2, label=f"{label}  h={d['h']:.0f} m  A={d['area']:.2f} km²"
        )

ctx.add_basemap(ax, source=ctx.providers.OpenStreetMap.Mapnik, attribution=False)
ax.set_title(f"{BIRD_ID} – Home Range KDE 95%")
ax.set_axis_off()
ax.legend()
plt.tight_layout()
plt.show()


print(f"\n{BIRD_ID} – KDE 95% Home Range Summary:")
print(" Method   h*(m)   Area(km²)")
for label, d in results.items():
    print(f" {label:6s}  {d['h']:6.0f}   {d['area']:7.2f}")

"""## k-Local Convex Hull Method (Section 3.3.3)

k-Local Convex Hull (k-LoCoH) constructs a range by combining convex hulls of local point clusters, using k nearest neighbours.

This method captures landscape structure and reveal travel corridors. However, this method is more complex and requires tuning of k. Finding an optimal k can be done using cross-validation, however much of the literature using 'rule of thumb', so we will follow with that by using a fixed k that can be tweaked by the user. We chose k=10 for a good trade-off between overestimation and underestimation, which gives a home range estimate of 0.32km^2
"""

K_LOCOH = 10      # choice of k
BIRD_ID = "A114"
FILE = "gps_data.csv"

df = pd.read_csv(FILE).dropna(subset=['location-lat', 'location-long'])
gdf = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(df['location-long'], df['location-lat']),
    crs="EPSG:4326"
)

# UTM zone
avg_longitude = df['location-long'].mean()
UTM_EPSG = 32600 + 1 + int((avg_longitude + 180) / 6)  # Northern hemisphere
gdf = gdf.to_crs(epsg=UTM_EPSG)

# Filter for individual Bird
gdf_A114 = gdf[gdf['individual-local-identifier'] == BIRD_ID]
xy = np.column_stack((gdf_A114.geometry.x, gdf_A114.geometry.y))

# LoCoH
nbr = NearestNeighbors(n_neighbors=K_LOCOH).fit(xy)
neigh_ix = nbr.kneighbors(return_distance=False)
hulls = [MultiPoint(xy[ix]).convex_hull for ix in neigh_ix]
hulls = [hull for hull in hulls if not hull.is_empty]  # Filter invalid hulls
locoh_poly = unary_union(hulls)
locoh_area = locoh_poly.area / 1e6  # Area in km²

# plot
fig, ax = plt.subplots(figsize=(10, 10))
gdf_A114_web = gdf_A114.to_crs(epsg=3857)  # Convert to Web Mercator
gdf_A114_web.plot(ax=ax, color='blue', markersize=5, label='GPS points')

locoh_web = gpd.GeoSeries([locoh_poly], crs=gdf.crs).to_crs(epsg=3857)
locoh_web.boundary.plot(ax=ax, edgecolor="green", linewidth=1.2, label=f"LoCoH k={K_LOCOH}")

# basemap
ctx.add_basemap(ax, source=ctx.providers.OpenStreetMap.Mapnik, attribution=False)
ax.set_title(f"{BIRD_ID} – Home Range k-LoCoH (Area: {locoh_area:.2f} km²)")
ax.set_axis_off()
ax.legend()
plt.tight_layout()
plt.show()

"""## Method Comparison (Section 3.3.4)

**Comparison**

MCP draws the smallest convex shape that covers all GPS points. This method is simple, which makes comparison of different birds easy. However, this method can overestimate the home range since it is very sensitive to outliers.

KDE puts points into a density surface and draws a contour (in our case, 95% contour). This method is useful for finding core areas and smooths random movements from the birds. However, this method can include areas that the bird has not visited. Also, the choice of bandwidth is critical to KDE.

k-LoCoH builds many small hulls based on the k nearest neighbours of points and merges them. This method is useful in capturing barriers (although this is not much of a worry with birds), it preserves fine structure, and is not affected much by outliers. However, this method is more complex, so it may be slower, and it requires a careful choice of k.

**Conclusion**

Overall, k-LoCoH gives a more realistic and ecologically significant home range for the birds. This method respects boundaries, such as urban areas, and it tightly hugs the points, with no smoothing beyond where the birds actually went. k-LoCoH can also show multiple core areas if the bird uses different patches, and avoids overestimation when a few exploratory points happen.
"""

BIRD_ID = "A114"
FILE = "gps_data.csv"
K_LOCOH = 10
LEVEL = 0.95
CELL = 250  # raster cell size for KDE

df = pd.read_csv(FILE).dropna(subset=['location-lat', 'location-long'])
gdf = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(df['location-long'], df['location-lat']),
    crs="EPSG:4326"
)

# UTM zone based on longitude
longitude = gdf.geometry.x.mean()
utm_zone = int((longitude + 180)/6) + 1
UTM_EPSG = 32600 + utm_zone  # northern hemisphere

# project to UTM
gdf_utm = gdf.to_crs(epsg=UTM_EPSG)

# filter individual bird
gdf_bird = gdf_utm[gdf_utm['individual-local-identifier'] == BIRD_ID]
xy = np.column_stack((gdf_bird.geometry.x, gdf_bird.geometry.y))

# MCP
hull = ConvexHull(xy)
hull_points = xy[hull.vertices]
mcp_poly = Polygon(hull_points)
mcp_area = mcp_poly.area / 1e6  # km²

# KDE (Scott's Rule)
def scott_bandwidth(xy):
    n, d = xy.shape
    factor = n ** (-1. / (d + 4))
    avg_std = np.std(xy, axis=0).mean()
    return factor * avg_std

def kde95_polygon(xy, h):
    kde = gaussian_kde(xy.T, bw_method=h/np.std(xy, 0).mean())
    xmin, ymin = xy.min(0) - 3*h
    xmax, ymax = xy.max(0) + 3*h
    nx = int((xmax - xmin)/CELL) + 1
    ny = int((ymax - ymin)/CELL) + 1
    xx, yy = np.mgrid[xmin:xmax:nx*1j, ymin:ymax:ny*1j]
    zz = kde(np.vstack([xx.ravel(), yy.ravel()])).reshape(xx.shape)
    threshold = np.percentile(zz, (1-LEVEL)*100)
    mask = (zz >= threshold).astype("uint8")
    shapes_iter = features.shapes(mask, transform=from_origin(xmin, ymax, CELL, CELL))
    polys = [shape(geom) for geom, val in shapes_iter if val == 1]
    return unary_union(polys) if polys else None

h_scott = scott_bandwidth(xy)
kde_poly = kde95_polygon(xy, h_scott)
kde_area = kde_poly.area / 1e6 if kde_poly else np.nan

# k-LoCoH
nbrs = NearestNeighbors(n_neighbors=K_LOCOH).fit(xy)
neigh_ix = nbrs.kneighbors(return_distance=False)
hulls = [MultiPoint(xy[ix]).convex_hull for ix in neigh_ix]
hulls = [hull for hull in hulls if not hull.is_empty]
locoh_poly = unary_union(hulls)
locoh_area = locoh_poly.area / 1e6

# Plot
fig, ax = plt.subplots(figsize=(12, 12))

# plot GPS points
gdf_bird.to_crs(3857).plot(ax=ax, color='black', markersize=5, label='GPS Points')

# plot MCP border
gpd.GeoSeries([mcp_poly], crs=gdf_utm.crs).to_crs(3857).boundary.plot(
    ax=ax, edgecolor='blue', linewidth=2, label=f'MCP (Area: {mcp_area:.2f} km²)'
)

# plot KDE border
if kde_poly:
    gpd.GeoSeries([kde_poly], crs=gdf_utm.crs).to_crs(3857).boundary.plot(
        ax=ax, edgecolor='red', linewidth=2, label=f'KDE-Scott (Area: {kde_area:.2f} km²)'
    )

# Plot k-LoCoH border
gpd.GeoSeries([locoh_poly], crs=gdf_utm.crs).to_crs(3857).boundary.plot(
    ax=ax, edgecolor='green', linewidth=2, label=f'k-LoCoH (Area: {locoh_area:.2f} km²)'
)

ctx.add_basemap(ax, source=ctx.providers.OpenStreetMap.Mapnik, attribution=False)

ax.set_title(f"{BIRD_ID} – Home Range Estimates")
ax.set_axis_off()
ax.legend()
plt.tight_layout()
plt.show()

"""## Full results (not included in main paper)"""

FILE = "gps_data.csv"
K_LOCOH = 10 # fixed k (can change to different values)
LEVEL = 0.95 # 95% contour (can change level)
CELL = 250  # Raster cell size for KDE

# read data and drop empty location rows
df = pd.read_csv(FILE).dropna(subset=['location-lat', 'location-long'])

# convert to GeoDataFrame
gdf = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(df['location-long'], df['location-lat']),
    crs="EPSG:4326"
)

# UTM zone based on mean longitude
longitude = gdf.geometry.x.mean()
utm_zone = int((longitude + 180)/6) + 1
UTM_EPSG = 32600 + utm_zone  # For Northern Hemisphere

# Project data to UTM
gdf_utm = gdf.to_crs(epsg=UTM_EPSG)

# using scott's rule to choose a bandwidth for KDE
def scott_bandwidth(xy):
    n, d = xy.shape
    factor = n ** (-1. / (d + 4))
    avg_std = np.std(xy, axis=0).mean()
    return factor * avg_std

# KDE: points (xy) & bandwidth (h)
def kde95_polygon(xy, h):
    kde = gaussian_kde(xy.T, bw_method=h/np.std(xy, 0).mean())
    # build a raster grid that is big enough for the data and add some padding
    xmin, ymin = xy.min(0) - 3*h
    xmax, ymax = xy.max(0) + 3*h
    nx = int((xmax - xmin)/CELL) + 1
    ny = int((ymax - ymin)/CELL) + 1
    # KDE over the grid
    xx, yy = np.mgrid[xmin:xmax:nx*1j, ymin:ymax:ny*1j]
    zz = kde(np.vstack([xx.ravel(), yy.ravel()])).reshape(xx.shape)
    # 95% threshold
    threshold = np.percentile(zz, (1-LEVEL)*100)
    mask = (zz >= threshold).astype("uint8")
    # takes the 95% contour and merges multiple shapes into one
    shapes_iter = features.shapes(mask, transform=from_origin(xmin, ymax, CELL, CELL))
    polys = [shape(geom) for geom, val in shapes_iter if val == 1]
    return unary_union(polys) if polys else None

# iterate through each bird
bird_ids = gdf_utm['individual-local-identifier'].unique()

# tracking points for each bird
for bird_id in bird_ids:
    bird = gdf_utm[gdf_utm['individual-local-identifier'] == bird_id]
    if bird.empty:
        continue
    # numpy array of X/Y coordinates
    xy = np.column_stack((bird.geometry.x, bird.geometry.y))

    # skip bird with too few points
    if len(xy) < 10:
        print(f"Skipping {bird_id}: too few points ({len(xy)})")
        continue

    # MCP
    try:
        hull = ConvexHull(xy)
        hull_points = xy[hull.vertices]
        mcp_poly = Polygon(hull_points)
        mcp_area = mcp_poly.area / 1e6  # km²
    except:
        print(f"Skipping {bird_id}: MCP calculation failed")
        continue

    # KDE (Scott)
    h_scott = scott_bandwidth(xy)
    kde_poly = kde95_polygon(xy, h_scott)
    kde_area = kde_poly.area / 1e6 if kde_poly else np.nan

    # k-LoCoH
    try:
        # find k nearest
        nbrs = NearestNeighbors(n_neighbors=K_LOCOH).fit(xy)
        neigh_ix = nbrs.kneighbors(return_distance=False)
        # build a small convex hull around each point and its neighbours
        hulls = [MultiPoint(xy[ix]).convex_hull for ix in neigh_ix]
        hulls = [hull for hull in hulls if not hull.is_empty]
        # merge all hulls
        locoh_poly = unary_union(hulls)
        locoh_area = locoh_poly.area / 1e6
    except:
        print(f"Skipping {bird_id}: LoCoH calculation failed")
        continue

    # plot
    fig, ax = plt.subplots(figsize=(12, 12))

    bird.to_crs(3857).plot(ax=ax, color='black', markersize=5, label='GPS Points')

    gpd.GeoSeries([mcp_poly], crs=gdf_utm.crs).to_crs(3857).boundary.plot(
        ax=ax, edgecolor='blue', linewidth=2, label=f'MCP (Area: {mcp_area:.2f} km²)'
    )

    if kde_poly:
        gpd.GeoSeries([kde_poly], crs=gdf_utm.crs).to_crs(3857).boundary.plot(
            ax=ax, edgecolor='red', linewidth=2, label=f'KDE-Scott (Area: {kde_area:.2f} km²)'
        )

    gpd.GeoSeries([locoh_poly], crs=gdf_utm.crs).to_crs(3857).boundary.plot(
        ax=ax, edgecolor='green', linewidth=2, label=f'k-LoCoH (Area: {locoh_area:.2f} km²)'
    )

    ctx.add_basemap(ax, source=ctx.providers.OpenStreetMap.Mapnik, attribution=False)

    ax.set_title(f"{bird_id} – Home Range Estimates")
    ax.set_axis_off()
    ax.legend()
    plt.tight_layout()

    plt.show()
